In [1]:
import pandas as pd
import numpy as np

In [2]:
ProcessedLocations = pd.read_csv("ImputedProvince.csv")

In [3]:
ProcessedLocations.head()
ProcessedLocations.set_index('Unnamed: 0')
ProcessedLocations.columns

Index(['Unnamed: 0', 'Province_State', 'Country_Region', 'Last_Update', 'Lat',
       'Long_', 'Confirmed', 'Deaths', 'Recovered', 'Active', 'Combined_Key',
       'Incidence_Rate', 'Case-Fatality_Ratio', 'geom'],
      dtype='object')

In [4]:
ProcessedLocations = ProcessedLocations.dropna(how='any',axis=0)

In [5]:
ProcessedLocations['Province'] = ProcessedLocations["Province_State"]
ProcessedLocations.drop('Unnamed: 0', axis=1, inplace=True)
ProcessedLocations

,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incidence_Rate,Case-Fatality_Ratio,geom,Province
0,Мурманская область,Afghanistan,2020-09-20 04:22:56,33.939110,67.709953,38919,1437,32576,4906.0,Afghanistan,99.976005,3.692284,"67.709953, 33.93911",Мурманская область
2,Ituri,Algeria,2020-09-20 04:22:56,28.033900,1.659600,49623,1665,34923,13035.0,Algeria,113.162645,3.355299,"1.6596, 28.0339",Ituri
3,Jubbada Dhexe جوبا الوسطى,Andorra,2020-09-20 04:22:56,42.506300,1.521800,1564,53,1164,347.0,Andorra,2024.202420,3.388747,"1.5218, 42.5063",Jubbada Dhexe جوبا الوسطى
4,العصابة,Angola,2020-09-20 04:22:56,-11.202700,17.873900,3901,147,1445,2309.0,Angola,11.869312,3.768265,"17.8739, -11.2027",العصابة
7,Адыгея,Armenia,2020-09-20 04:22:56,40.069100,45.038200,47154,928,42551,3675.0,Armenia,1591.301936,1.968020,"45.0382, 40.0691",Адыгея
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,El Bayadh ⵍⴱⴻⵢⴻⴹ البيض,Uganda,2020-09-20 04:22:56,1.373333,32.290275,6017,63,2581,3373.0,Uganda,13.154500,1.047033,"32.290275, 1.373333",El Bayadh ⵍⴱⴻⵢⴻⴹ البيض
156,województwo podlaskie,United Arab Emirates,2020-09-20 04:22:56,23.424076,53.847818,84242,404,73512,10326.0,United Arab Emirates,851.755237,0.479571,"53.847818, 23.424076",województwo podlaskie
158,Архангельская область,Uzbekistan,2020-09-20 04:22:56,41.377491,64.585262,50992,427,47271,3294.0,Uzbekistan,152.355006,0.837386,"64.585262, 41.377491",Архангельская область
162,North-Western Province,Western Sahara,2020-09-20 04:22:56,24.215500,-12.885800,10,1,8,1.0,Western Sahara,1.674116,10.000000,"-12.8858, 24.2155",North-Western Province
163,Niederösterreich,Yemen,2020-09-20 04:22:56,15.552727,48.516388,2026,585,1221,220.0,Yemen,6.792738,28.874630,"48.516388, 15.552727",Niederösterreich

In [6]:
DataFrameNan = pd.read_csv("dataset/processed_location_Sep20th2020.csv")

In [7]:
DataFrameNan = DataFrameNan[DataFrameNan['Province_State'].notna()]
DataFrameNan

,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incidence_Rate,Case-Fatality_Ratio
8,Australian Capital Territory,Australia,2020-09-20 04:22:56,-35.4735,149.0124,113,3,110,0.0,"Australian Capital Territory, Australia",26.395702,2.654867
9,New South Wales,Australia,2020-09-20 04:22:56,-33.8688,151.2093,4200,53,2994,1153.0,"New South Wales, Australia",51.736881,1.261905
10,Northern Territory,Australia,2020-09-20 04:22:56,-12.4634,130.8456,33,0,31,2.0,"Northern Territory, Australia",13.436482,0.000000
11,Queensland,Australia,2020-09-20 04:22:56,-27.4698,153.0251,1152,6,1123,23.0,"Queensland, Australia",22.519793,0.520833
12,South Australia,Australia,2020-09-20 04:22:56,-34.9285,138.6007,466,4,462,0.0,"South Australia, Australia",26.530031,0.858369
...,...,...,...,...,...,...,...,...,...,...,...,...
3940,Northern Ireland,United Kingdom,2020-09-20 04:22:56,54.7877,-6.4923,9165,575,0,8590.0,"Northern Ireland, United Kingdom",487.085459,6.273868
3941,Scotland,United Kingdom,2020-09-20 04:22:56,56.4907,-4.2026,24126,2505,0,21621.0,"Scotland, United Kingdom",441.601230,10.382989
3942,Turks and Caicos Islands,United Kingdom,2020-09-20 04:22:56,21.6940,-71.7979,668,5,572,91.0,"Turks and Caicos Islands, United Kingdom",1725.295728,0.748503
3943,Unknown,United Kingdom,2020-09-20 04:22:56,NaN,NaN,0,0,0,0.0,"Unknown, United Kingdom",NaN,NaN
3944,Wales,United Kingdom,2020-09-20 04:22:56,52.1307,-3.7837,20445,1603,0,18842.0,"Wales, United Kingdom",651.405085,7.840548

In [8]:
df3 = pd.concat([ProcessedLocations, DataFrameNan])
df3

,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incidence_Rate,Case-Fatality_Ratio,geom,Province
0,Мурманская область,Afghanistan,2020-09-20 04:22:56,33.93911,67.709953,38919,1437,32576,4906.0,Afghanistan,99.976005,3.692284,"67.709953, 33.93911",Мурманская область
2,Ituri,Algeria,2020-09-20 04:22:56,28.03390,1.659600,49623,1665,34923,13035.0,Algeria,113.162645,3.355299,"1.6596, 28.0339",Ituri
3,Jubbada Dhexe جوبا الوسطى,Andorra,2020-09-20 04:22:56,42.50630,1.521800,1564,53,1164,347.0,Andorra,2024.202420,3.388747,"1.5218, 42.5063",Jubbada Dhexe جوبا الوسطى
4,العصابة,Angola,2020-09-20 04:22:56,-11.20270,17.873900,3901,147,1445,2309.0,Angola,11.869312,3.768265,"17.8739, -11.2027",العصابة
7,Адыгея,Armenia,2020-09-20 04:22:56,40.06910,45.038200,47154,928,42551,3675.0,Armenia,1591.301936,1.968020,"45.0382, 40.0691",Адыгея
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3940,Northern Ireland,United Kingdom,2020-09-20 04:22:56,54.78770,-6.492300,9165,575,0,8590.0,"Northern Ireland, United Kingdom",487.085459,6.273868,NaN,NaN
3941,Scotland,United Kingdom,2020-09-20 04:22:56,56.49070,-4.202600,24126,2505,0,21621.0,"Scotland, United Kingdom",441.601230,10.382989,NaN,NaN
3942,Turks and Caicos Islands,United Kingdom,2020-09-20 04:22:56,21.69400,-71.797900,668,5,572,91.0,"Turks and Caicos Islands, United Kingdom",1725.295728,0.748503,NaN,NaN
3943,Unknown,United Kingdom,2020-09-20 04:22:56,NaN,NaN,0,0,0,0.0,"Unknown, United Kingdom",NaN,NaN,NaN,NaN
3944,Wales,United Kingdom,2020-09-20 04:22:56,52.13070,-3.783700,20445,1603,0,18842.0,"Wales, United Kingdom",651.405085,7.840548,NaN,NaN

In [11]:
df3.drop(['geom', 'Province'], axis=1, inplace=True)

In [13]:
df3.isnull().sum(axis = 0)

Province_State          0
Country_Region          0
Last_Update             0
Lat                    78
Long_                  78
Confirmed               0
Deaths                  0
Recovered               0
Active                  2
Combined_Key            0
Incidence_Rate         78
Case-Fatality_Ratio    48
dtype: int64

In [16]:
LatLong = df3[df3['Lat'].isnull()]
LatLong = LatLong[~LatLong.Province_State.str.contains("Unknown")]

In [19]:
LatLong.to_csv("LatLongMissing.csv")

In [20]:
ImputedLat_Long = pd.read_csv("ImputedLongLat.csv")

In [22]:
ImputedLat_Long = ImputedLat_Long[ImputedLat_Long['Lat'] != 0]

In [24]:
df3 = df3[df3['Lat'].notna()]

In [26]:
LongLatitudeImputation = pd.concat([df3, ImputedLat_Long])

In [30]:
LongLatitudeImputation.drop(['Unnamed: 0', 'Unnamed: 0.1'], axis=1, inplace=True)

In [31]:
LongLatitudeImputation.isnull().sum(axis = 0)

Province_State          0
Country_Region          0
Last_Update             0
Lat                     0
Long_                   0
Confirmed               0
Deaths                  0
Recovered               0
Active                  1
Combined_Key            0
Incidence_Rate         70
Case-Fatality_Ratio    44
dtype: int64

In [32]:
Incidence_Rate = LongLatitudeImputation[LongLatitudeImputation['Incidence_Rate'].isnull()]

In [34]:
Incidence_Rate.to_csv("MissingIncidenceRate.csv")

In [36]:
ImputedIncidenceRate = pd.read_csv("ImputedIncidenceRate.csv")

In [38]:
IncidenceRatePresent = LongLatitudeImputation[LongLatitudeImputation['Incidence_Rate'].notna()]

In [41]:
JoinedTable = pd.concat([IncidenceRatePresent, ImputedIncidenceRate])
JoinedTable.drop(['Unnamed: 0', 'Unnamed: 0.1','Population'], axis=1, inplace=True)

In [60]:
JoinedTable.isnull().sum(axis = 0)
JoinedTable

,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incidence_Rate,Case-Fatality_Ratio
0,Мурманская область,Afghanistan,2020-09-20 04:22:56,33.939110,67.709953,38919,1437,32576,4906.0,Afghanistan,99.976005,3.692284
2,Ituri,Algeria,2020-09-20 04:22:56,28.033900,1.659600,49623,1665,34923,13035.0,Algeria,113.162645,3.355299
3,Jubbada Dhexe جوبا الوسطى,Andorra,2020-09-20 04:22:56,42.506300,1.521800,1564,53,1164,347.0,Andorra,2024.202420,3.388747
4,العصابة,Angola,2020-09-20 04:22:56,-11.202700,17.873900,3901,147,1445,2309.0,Angola,11.869312,3.768265
7,Адыгея,Armenia,2020-09-20 04:22:56,40.069100,45.038200,47154,928,42551,3675.0,Armenia,1591.301936,1.968020
...,...,...,...,...,...,...,...,...,...,...,...,...
65,Virginia,US,2020-09-20 04:22:56,37.123224,-78.492772,0,0,0,0.0,"Unassigned, Virginia, US",0.000000,NaN
66,Washington,US,2020-09-20 04:22:56,38.894992,-77.036558,292,5,0,287.0,"Unassigned, Washington, US",0.091462,1.712329
67,West Virginia,US,2020-09-20 04:22:56,38.475841,-80.840842,0,0,0,0.0,"Unassigned, West Virginia, US",0.000000,NaN
68,Wisconsin,US,2020-09-20 04:22:56,44.430898,-89.688464,0,0,0,0.0,"Unassigned, Wisconsin, US",0.000000,NaN
69,Wyoming,US,2020-09-20 04:22:56,43.170026,-107.568535,1,0,0,0.0,"Unassigned, Wyoming, US",0.000313,0.000000

In [66]:
Ratio = JoinedTable[JoinedTable['Case-Fatality_Ratio'].isnull()]
CleanedData = JoinedTable[JoinedTable['Case-Fatality_Ratio'].notna()]

In [67]:
Ratio['Case-Fatality_Ratio'] = Ratio['Case-Fatality_Ratio'].fillna(0)

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [68]:
CleanedData.isnull().sum(axis = 0)

Province_State         0
Country_Region         0
Last_Update            0
Lat                    0
Long_                  0
Confirmed              0
Deaths                 0
Recovered              0
Active                 0
Combined_Key           0
Incidence_Rate         0
Case-Fatality_Ratio    0
dtype: int64

In [69]:
Ratio.dropna(subset = ["Active"], inplace=True)

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [70]:
FinalCleanedData = pd.concat([Ratio, CleanedData])
FinalCleanedData = FinalCleanedData.reset_index(drop=True)
FinalCleanedData.to_csv("dataset/CleanedLocations.csv")