In [10]:
import pandas as pd
import numpy as np

In [11]:
ProcessedLocations = pd.read_csv("ImputedProvince.csv")

In [12]:
ProcessedLocations.head()
ProcessedLocations.set_index('Unnamed: 0')
ProcessedLocations.columns

Index(['Unnamed: 0', 'Province_State', 'Country_Region', 'Last_Update', 'Lat',
       'Long_', 'Confirmed', 'Deaths', 'Recovered', 'Active', 'Combined_Key',
       'Incidence_Rate', 'Case-Fatality_Ratio', 'geom'],
      dtype='object')

In [13]:
ProcessedLocations = ProcessedLocations.dropna(how='any',axis=0)

In [14]:
ProcessedLocations['Province'] = ProcessedLocations["Province_State"]
ProcessedLocations

,Unnamed: 0,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incidence_Rate,Case-Fatality_Ratio,geom,Province
0,0,Мурманская область,Afghanistan,2020-09-20 04:22:56,33.939110,67.709953,38919,1437,32576,4906.0,Afghanistan,99.976005,3.692284,"67.709953, 33.93911",Мурманская область
2,2,Ituri,Algeria,2020-09-20 04:22:56,28.033900,1.659600,49623,1665,34923,13035.0,Algeria,113.162645,3.355299,"1.6596, 28.0339",Ituri
3,3,Jubbada Dhexe جوبا الوسطى,Andorra,2020-09-20 04:22:56,42.506300,1.521800,1564,53,1164,347.0,Andorra,2024.202420,3.388747,"1.5218, 42.5063",Jubbada Dhexe جوبا الوسطى
4,4,العصابة,Angola,2020-09-20 04:22:56,-11.202700,17.873900,3901,147,1445,2309.0,Angola,11.869312,3.768265,"17.8739, -11.2027",العصابة
5,5,NF,Antigua and Barbuda,2020-09-20 04:22:56,17.060800,-61.796400,96,3,92,1.0,Antigua and Barbuda,98.031207,3.125000,"-61.7964, 17.0608",NF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,3948,NF,Vietnam,2020-09-20 04:22:56,14.058324,108.277199,1068,35,942,91.0,Vietnam,1.097201,3.277154,"108.277199, 14.058324",NF
161,3949,NF,West Bank and Gaza,2020-09-20 04:22:56,31.952200,35.233200,35003,253,23446,11304.0,West Bank and Gaza,686.142828,0.722795,"35.2332, 31.9522",NF
162,3950,North-Western Province,Western Sahara,2020-09-20 04:22:56,24.215500,-12.885800,10,1,8,1.0,Western Sahara,1.674116,10.000000,"-12.8858, 24.2155",North-Western Province
163,3951,Niederösterreich,Yemen,2020-09-20 04:22:56,15.552727,48.516388,2026,585,1221,220.0,Yemen,6.792738,28.874630,"48.516388, 15.552727",Niederösterreich
165,3953,NF,Zimbabwe,2020-09-20 04:22:56,-19.015438,29.154857,7672,225,5914,1533.0,Zimbabwe,51.618366,2.932742,"29.154857, -19.015438",NF

In [43]:
Index_List = ProcessedLocations['Unnamed: 0'].values.tolist()
Values_List = ProcessedLocations['Province_State'].values.tolist()
Index_List

[0,
 2,
 3,
 4,
 5,
 6,
 7,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 29,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 79,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 172,
 175,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 186,
 187,
 188,
 189,
 200,
 202,
 203,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 232,
 270,
 271,
 272,
 273,
 274,
 296,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 403,
 404,
 405,
 407,
 408,
 409,
 410,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 442,
 443,
 444,
 471,
 472,
 474,
 559,
 560,
 561,
 562,
 563,
 564,
 566,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 596,
 597,
 598,
 620,
 622,
 623,
 625,
 626,
 627,
 628,
 629,
 630,
 3901,
 3929,
 3945,
 3946,
 3947,
 3948,
 3949,
 3950,
 3951,
 3953]

In [44]:
DataFrameNan = pd.read_csv("dataset/processed_location_Sep20th2020.csv")

In [45]:
DataFrameNan

,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incidence_Rate,Case-Fatality_Ratio
0,NaN,Afghanistan,2020-09-20 04:22:56,33.939110,67.709953,38919,1437,32576,4906.0,Afghanistan,99.976005,3.692284
1,NaN,Albania,2020-09-20 04:22:56,41.153300,20.168300,12226,358,6888,4980.0,Albania,424.838418,2.928186
2,NaN,Algeria,2020-09-20 04:22:56,28.033900,1.659600,49623,1665,34923,13035.0,Algeria,113.162645,3.355299
3,NaN,Andorra,2020-09-20 04:22:56,42.506300,1.521800,1564,53,1164,347.0,Andorra,2024.202420,3.388747
4,NaN,Angola,2020-09-20 04:22:56,-11.202700,17.873900,3901,147,1445,2309.0,Angola,11.869312,3.768265
...,...,...,...,...,...,...,...,...,...,...,...,...
3949,NaN,West Bank and Gaza,2020-09-20 04:22:56,31.952200,35.233200,35003,253,23446,11304.0,West Bank and Gaza,686.142828,0.722795
3950,NaN,Western Sahara,2020-09-20 04:22:56,24.215500,-12.885800,10,1,8,1.0,Western Sahara,1.674116,10.000000
3951,NaN,Yemen,2020-09-20 04:22:56,15.552727,48.516388,2026,585,1221,220.0,Yemen,6.792738,28.874630
3952,NaN,Zambia,2020-09-20 04:22:56,-13.133897,27.849332,14070,330,13365,375.0,Zambia,76.534126,2.345416
3953,NaN,Zimbabwe,2020-09-20 04:22:56,-19.015438,29.154857,7672,225,5914,1533.0,Zimbabwe,51.618366,2.932742

In [46]:
new_column = pd.Series({'Province_State': Value_List}, index=Index_List)
DataFrameNan = DataFrameNan.update(new_column)

In [47]:
DataFrameNan

In [23]:
DataFrameNan.dropna(how="any", inplace=True)
DataFrameNan = DataFrameNan.fillna("", inplace=False)

AttributeError: 'NoneType' object has no attribute 'dropna'